Rework 'Thesis' section
securityinmobility/security.science pull request #17
Opened 2024-12-17 11:54 UTC by dominikbayerl

Changes:
- Move theses to their own section (81934da4cc3fcce6a4b56df52bbfdeec9974b50c)
- Remove outdated thesis offerings (d3d7cf8126823b35e7856cfeb2410b036adeaee1 @kvn-myr)
- Move Profile pictures to Site Resources (instead of Page Resources), but I want to reuse them on other pages (36a4a9f26fb6199f996b0ba520173b4c1c3ed8d4)

2024-12-18 08:00 UTC, M4GNV5 reviewed
not sure if this restructuring was necessary just to add details to one thesis, especially since now all thesis are clickable, but 90% have to details, so after clicking one or two options nobody will check the details anymore.

2024-12-18 08:04 UTC, M4GNV5 requested changes
Contact card for Dominik:
![image](https://github.com/user-attachments/assets/d4d8f413-ca3b-4a8f-9289-db9f928a3be9)


Contact card for Thomas and me:
![image](https://github.com/user-attachments/assets/0e4163f3-58e5-4c9a-87f6-eb7e646cafb5)


Maybe consider using the contact cards from the contact page by moving them to modules, allowing us to list the same links on the thesis pages as on the dashboard.
Would require us to add E-Mail addresses there though

2024-12-18 08:19 UTC, dominikbayerl commented
> not sure if this restructuring was necessary just to add details to one thesis, especially since now all thesis are clickable, but 90% have to details, so after clicking one or two options nobody will check the details anymore.

Feel free to add details to your thesis topics! :-)

2025-01-22 10:35 UTC, M4GNV5 approved these changes
tested this locally. Looks much better now.

2025-01-22 10:36 UTC, merged